"""ChiEAC Impact: aggregated, anonymized insights (synthetic demo data)."""

import streamlit as st

from career_insights import charts, impact
from career_insights.ui import demo_banner, disclaimer, get_data, show, source_caption

ds, _model = get_data()

st.title("ChiEAC Impact")
st.markdown("Aggregated trends across career profiles: which skills students bring, which roles they aim for, where "
            "they are, and how skills gaps change over time.")
demo_banner("**Demonstration data.** These charts use synthetic profiles generated for this demo. They are **not** "
            "official ChiEAC data and do not describe real students or program outcomes.")
st.success("**Privacy:** no personally identifiable information is displayed or stored. Only aggregate counts "
           f"are shown, and any group with fewer than {impact.MIN_GROUP_SIZE} profiles is suppressed.",
           icon=":material/shield_lock:")

try:
    metrics = impact.headline_metrics(ds)
except Exception as exc:
    st.error(f"Impact statistics could not be computed: {exc}")
    st.stop()

m1, m2, m3, m4 = st.columns(4)
m1.metric("Profiles analyzed", f"{metrics['profiles']:,}")
m2.metric("Most common skill", metrics["top_skill"])
m3.metric("Most desired role", metrics["top_occupation"])
m4.metric("Most common location", metrics["top_location"])
st.caption(f"Cohorts {metrics['quarters'][0]} to {metrics['quarters'][-1]}.")

left, right = st.columns(2, gap="large")
with left:
    show(charts.simple_bar(impact.top_skills(ds), "share_pct", "skill", "Most common skills (% of profiles)",
                           "Share of profiles (%)", color=charts.TEAL, suffix="%"), key="top_skills")
with right:
    occ = impact.top_occupations(ds)
    show(charts.simple_bar(occ, "profiles", "occupation", "Most requested target roles", "Profiles",
                           color=charts.BLUE), key="top_occ")

geo = impact.geographic_distribution(ds)
g1, g2 = st.columns([3, 2], gap="large")
with g1:
    show(charts.geo_bubbles(geo, "Geographic distribution of profiles"), key="geo")
with g2:
    show(charts.simple_bar(geo, "share_pct", "short_name", "Profiles by metro area (%)", "Share (%)",
                           color=charts.NAVY, suffix="%"), key="geo_bar")

st.subheader("Skills gap trends")
trend = impact.gap_trend_by_quarter(ds)
show(charts.trend_lines(trend), key="trend")
st.caption("Readiness is the importance-weighted share of each profile's target-role skills that it covers, "
           "averaged per cohort. Missing core skills are skills rated 4–5 for the target role.")

heat = impact.missing_core_heatmap(ds)
show(charts.heatmap(heat, "Share of profiles missing each core skill, by target role (%)", "% missing", ".0f",
                    zmin=0, zmax=100), key="gap_heat")
st.caption("Blank cells mean the skill is not core for that role. Roles with fewer than "
           f"{impact.MIN_GROUP_SIZE} profiles are hidden.")
source_caption(ds, "demo_profiles", "occupation_skills")

with st.expander("How these statistics protect privacy", icon=":material/policy:"):
    st.markdown(f"""
* **No identifiers.** The underlying file holds only a random record ID, cohort quarter, metro area,
  education level, field of study, target role and skills. It has no names, emails, birthdates,
  nationality, visa status or free text.
* **Aggregates only.** This page shows counts, shares and averages. It never shows individual rows.
* **Small-cell suppression.** Any group with fewer than {impact.MIN_GROUP_SIZE} profiles is removed before
  display, so rare combinations cannot single anyone out.
* **Synthetic in this demo.** The records were generated by `scripts/build_demo_data.py`. To use real
  ChiEAC data, see the README section on privacy and data governance.
""")

disclaimer()
